services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 8180:8180           # qbittorrent
      - 6881:6881           # qbittorrent
      - 6881:6881/udp       # qbittorrent
      - 9696:9696           # prowlarr
      - 6789:6789           # nzbget
      - 6969:6969           # whisparr
      - 7878:7878           # radarr
      - 8989:8989           # sonarr
      - 6767:6767           # bazarr
      - 9999:9999           # stash
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /home/skynet/docker/gluetun/data:/gluetun
    environment:
      - TZ=America/Sao_Paulo
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=aNs4rdak0tPIop4FC7ct088D1VkNVq0OM0CkDT14X1E=
      - SERVER_COUNTRIES=Brazil
      
  qbittorrent:
    image: hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    volumes:
      - /home/skynet/docker/qbittorrent/config:/config
      - /mnt/usbhdd/data/torrents:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - WEBUI_PORTS=8180
      - TORRENTING_PORT=6881
      
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    volumes:
      - /home/skynet/docker/nbzget/data:/config
      - /mnt/usbhdd/data/torrents:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - NZBGET_USER=skynet
      - NZBGET_PASS=skynet29081997
    
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    volumes:
      - /home/skynet/docker/prowlarr/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo

  whisparr:
    image: ghcr.io/hotio/whisparr
    container_name: whisparr
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    volumes:
      - /home/skynet/docker/whisparr/data:/config
      - /mnt/usbhdd/data/media/XXX:/data
      - /mnt/usbhdd/data/torrents:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    volumes:
      - /home/skynet/docker/radarr/config:/config
      - /mnt/usbhdd/data:/data
      - /mnt/usbhdd/data/torrents:/downloads
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=America/Sao_Paulo

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    volumes:
      - /home/skynet/docker/sonarr/data:/config
      - /mnt/usbhdd/data/:/data
      - /mnt/usbhdd/data/torrents:/downloads
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=America/Sao_Paulo

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    volumes:
      - /home/skynet/docker/bazarr/config:/config
      - /mnt/usbhdd/data:/data
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=America/Sao_Paulo

  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    volumes:
      - /home/skynet/stash/config:/root/.stash
      - /mnt/usbhdd/data/media/XXX:/data
      - /mnt/usbhdd/data/DockerData/stash/metadata:/metadata
      - /mnt/usbhdd/data/DockerData/stash/cache:/cache
      - /mnt/usbhdd/data/DockerData/stash/blobs:/blobs
      - /mnt/usbhdd/data/DockerData/stash/generated:/generated
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - TZ=America/Sao_Paulo